### ISSUE TITLE
Latest 'release' fails to start (but master works)

### ISSUE THREAD

**Issue by Athanasius** [tezw21/BGS-Tally-v3#4]
Using the 3.0 (latest) .zip file the plugin fails to start.  I'm using and EDMC development (not actually `develop` in this case) branch, but the changes in it are only to do with the Inara plugin.

The current `master` 41621187f1fd373017dd09ab254826072f6803a2 does work, you probably just want to make a 3.1 release ?

Also, you could address those config.get() deprecation warnings ;)

```python
2021-06-03 17:18:35.071 - ERROR - 9296:8784:8784 plug.Plugin.__init__:61: : Failed for Plugin "BGS-Tally-v3-3.0"
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\plug.py", line 52, in __init__
    newname = module.plugin_start3(os.path.dirname(loadfile))
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally-v3-3.0\load.py", line 116, in plugin_start3
    return plugin_start(plugin_dir)
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally-v3-3.0\load.py", line 99, in plugin_start
    tick = response.json()
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Python39-32\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python39-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python39-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-06-03 17:18:35.083 - ERROR - 9296:8784:8784 plug.load_plugins:158: Failure loading found Plugin "BGS-Tally-v3-3.0"
Traceback (most recent call last):
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\plug.py", line 156, in load_plugins
    found.append(Plugin(name, os.path.join(config.plugin_dir_path, name, 'load.py'), plugin_logger))
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\plug.py", line 52, in __init__
    newname = module.plugin_start3(os.path.dirname(loadfile))
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally-v3-3.0\load.py", line 116, in plugin_start3
    return plugin_start(plugin_dir)
  File "C:\Users\Athan\AppData\Local\EDMarketConnector\plugins\BGS-Tally-v3-3.0\load.py", line 99, in plugin_start
    tick = response.json()
  File "C:\Users\Athan\Documents\Devel\EDMarketConnector\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Python39-32\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python39-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python39-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Athanasius** [comment]
I've been made aware that this repo is/was a work in progress, and am now using v2.2.0 from the other repo.

Perhaps add some **big bold text** to the README to indicate the state of this repo?
